
services:

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis_dev:/data
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
    networks:
      - proxy-net

networks:
  proxy-net:
    name: internal_network
